version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: django
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/project
      - pgsocket:/var/run/postgresql/
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    hostname: django.ass

  postgres:
    image: postgres:15.5-bookworm
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgsocket:/var/run/postgresql/
      - redissocket:/tmp/redis/
    env_file:
      - .env
    hostname: postgres.ass
    restart: unless-stopped

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    command: bash -c "npx webpack --config webpack.config.js
                                  --mode development 
                                  --watch"
    container_name: node
    env_file:
      - .env
    volumes:
      - .:/project
    hostname: npm.ass

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    command: redis-server /etc/redis.conf
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/var/lib/redis/
      - redissocket:/tmp/redis/
    env_file:
      - .env

volumes:
  pgdata:
  pgsocket:
  redissocket:
  redisdata: