version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: django
    command: bash -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/project
      - pgsocket:/var/run/postgresql/
    depends_on:
      - db
    env_file:
      - .env
    hostname: django.ass

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - pgsocket:/var/run/postgresql/
    env_file:
      - .env
    hostname: postgres.ass
    restart: unless-stopped

  npm:
    build:
      context: .
      dockerfile: Dockerfile.npm
    command: bash -c "npx webpack --config webpack.config.js
                                  --mode development 
                                  --watch"
    container_name: npm
    env_file:
      - .env
    volumes:
      - .:/project
    hostname: npm.ass


volumes:
  pgdata:
  pgsocket:
