# Generated by Django 5.0rc1 on 2023-11-22 17:48

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('context', models.CharField(max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='id_menuitem')],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField()),
                ('name', models.CharField(max_length=253)),
                ('remote', models.BooleanField(verbose_name='is remote host')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
                'indexes': [models.Index(fields=['id'], name='id_host')],
            },
            managers=[
                ('hosts', django.db.models.manager.Manager()),
            ],
        ),
    ]
