# Generated by Django 5.0rc1 on 2023-11-22 23:21

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('path', models.URLField(default='/', verbose_name='url path')),
                ('context', models.CharField(choices=[('SB', 'Sidebar')], max_length=2)),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(unique=True, verbose_name='host ip address')),
                ('name', models.CharField(max_length=253, unique=True, verbose_name='hostname')),
                ('remote', models.BooleanField(editable=False, verbose_name='is remote host')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='last update on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'host',
                'verbose_name_plural': 'hosts',
                'managed': True,
            },
            managers=[
                ('remote_hosts', django.db.models.manager.Manager()),
            ],
        ),
    ]
